name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Allow pushing commits and creating branches
      pull-requests: write # Allow modifying PRs, adding labels, assignees
      issues: write        # Allow modifying issues
      id-token: write
      actions: read        # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # For PRs, checkout the PR branch instead of the merge commit
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0  # Full history for better git operations

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # Grant additional permissions
          additional_permissions: |
            actions: read
          
          # Optional: Customize the trigger phrase (default: @claude)
          # trigger_phrase: "/claude"
          
          # Optional: Trigger when specific user is assigned to an issue
          # assignee_trigger: "evgenygurin"
          
          # Configure Claude's behavior with CLI arguments
          claude_args: |
            --model claude-3-5-haiku-20241022
            --max-turns 10
            --allowedTools "Bash,Read,Write,Edit,MultiEdit"
            --system-prompt "You are a helpful code reviewer for the Claude Code UI Next.js project. Focus on code quality, security, and best practices. Be thorough but constructive in your feedback."
          
          # Optional: Advanced settings configuration
          # settings: |
          #   {
          #     "env": {
          #       "NODE_ENV": "test"
          #     }
          #   }