name: Auto Assign PR

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write
  issues: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign PR to author
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Automatically assign PR to its author
            try {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                assignees: [context.payload.pull_request.user.login]
              });
              console.log(`✅ Assigned PR to @${context.payload.pull_request.user.login}`);
            } catch (error) {
              console.log('Could not assign PR:', error.message);
            }
            
            // Add review labels
            try {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['needs-review', 'claude-enabled']
              });
              console.log('✅ Added review labels');
            } catch (error) {
              console.log('Could not add labels:', error.message);
            }
            
            // Post welcome comment with Claude instructions
            try {
              const comment = `## 🤖 Claude Code Review Assistant
            
              This PR is ready for review! Claude will automatically review your changes.
              
              ### How to interact with Claude:
              
              Simply mention \`@claude\` in any comment to get assistance:
              
              - \`@claude review this\` - Get a detailed code review
              - \`@claude fix conflicts\` - Help resolve merge conflicts
              - \`@claude suggest improvements\` - Get optimization suggestions
              - \`@claude explain this code\` - Get explanations of complex code
              - \`@claude update docs\` - Help update documentation
              
              ### Automatic Review
              
              Claude has been triggered to automatically review this PR. You'll see the review comments shortly.
              
              ---
              *Need help? Just ask @claude!*`;
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: comment
              });
              console.log('✅ Posted welcome comment');
            } catch (error) {
              console.log('Could not post comment:', error.message);
            }