name: Claude Auto Review

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  review:
    # Skip drafts
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # For PRs, checkout the PR branch for accurate review
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0  # Full history for better analysis

      - name: Run Claude Auto Review
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # Enable visual progress tracking
          track_progress: true
          
          # Grant additional permissions for reading CI results
          additional_permissions: |
            actions: read
          
          # Comprehensive review prompt
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}
            PR TITLE: ${{ github.event.pull_request.title }}
            PR AUTHOR: ${{ github.event.pull_request.user.login }}
            
            Please perform a comprehensive code review of this pull request.
            
            ## Review Checklist:
            
            ### Code Quality
            - [ ] Code follows Next.js and React best practices
            - [ ] TypeScript types are properly defined
            - [ ] No commented-out code or debug statements
            - [ ] Meaningful variable and function names
            - [ ] DRY principle followed
            
            ### Testing & Security
            - [ ] Unit tests for new functions (if applicable)
            - [ ] No hardcoded credentials or sensitive data
            - [ ] Input validation implemented
            - [ ] Proper error handling
            
            ### Performance
            - [ ] No unnecessary re-renders (React)
            - [ ] Efficient data fetching patterns
            - [ ] Bundle size considerations
            - [ ] Lazy loading where appropriate
            
            ### Documentation
            - [ ] Code is self-documenting with clear logic
            - [ ] Complex logic has inline comments
            - [ ] README updated if needed
            
            Provide detailed feedback using inline comments for specific issues.
            Post a summary comment with your overall assessment.
            
            Note: The PR branch is already checked out in the current working directory.
          
          # Configure Claude's tools and behavior
          claude_args: |
            --model claude-3-5-haiku-20241022
            --max-turns 15
            --allowedTools "Bash,Read,Write,Edit"
            --system-prompt "You are an expert code reviewer for a Next.js project. Be thorough but constructive. Focus on actionable feedback."